### ISSUE TITLE
gitlab service failed to start in RHEL6

### ISSUE THREAD

**Issue by liouxiao** [atomic-penguin/cookbook-gitlab#72]
I use RHEL6, my `/etc/sudoers` is set with default value:

```
Defaults requiretty
```

When I redirect the console output to a log file and run `chef-client` in `cloud-init` to install gitlab (cookbook version 6.4.6), it fails to start gitlab service at the last step:

```
Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '1'
---- Begin output of /sbin/service gitlab start ----
STDOUT: 
STDERR: sudo: sorry, you must have a tty to run sudo
---- End output of /sbin/service gitlab start ----
Ran /sbin/service gitlab start returned 1
```

After google, I found a page reported similar issue at https://github.com/WASdev/ci.chef.wlp/issues/9%E2%80%8E

Hence I change the template file `gitlab.init.erb` from

```bash
# Switch to the app_user if it is not he/she who is running the script.
if [ "$USER" != "$app_user" ]; then
  sudo -u "$app_user" -H -i $0 "$@"; exit;
fi
```

to
```bash
# Switch to the app_user if it is not he/she who is running the script.
if [ "$USER" != "$app_user" ]; then
  exec su - "$app_user" -- $0 "$@"; exit;
fi
```

it seems to slove my problem.

**Comment by jeremyolliver** [comment]
This correction appears to be merged into the init scripts since (see [gitlab.init.erb](https://github.com/atomic-penguin/cookbook-gitlab/blob/701b11404a85f65c0b5a9b3f3a1524fa48df1512/templates/default/gitlab.init.erb#L42-L45)) so I'll close off this issue. Please re-open if there's still issues
