### ISSUE TITLE
Add ldap user_filter support

### ISSUE THREAD

**Issue by karcaw** [atomic-penguin/cookbook-gitlab#82]
Please add support for setting the user_filter ldap setting in the gitlab.yml config file, such that i can specify:
node.default['gitlab']['ldap']['user_filter'] = '(memberOf=cn=group1,dc=subdom,dc=example,dc=com)'

**Comment by jeremyolliver** [comment]
Hi, this option has recently been added to the master branch of this cookbook along with updating the gitlab version to 7.7-stable branch. Please give it a try
