### ISSUE TITLE
QUESTION: any plans to update this cookbook or transition to omnibus install?

### ISSUE THREAD

**Issue by epcim** [atomic-penguin/cookbook-gitlab#85]
Eric, any plans to update this cookbook to latest gitlab?

As of omnibus is now an official install method and a chef cookbook exist to employ it https://gitlab.com/gitlab-org/cookbook-omnibus-gitlab/blob/master/README.md (even not properly updated)

Optionally does anybody has any comments what's needed to switch from this cookbook to the cookbook-omnibus-gitlab?

Thanks

**Comment by atomic-penguin** [comment]
Yeah, I do plan to update it.  I know its in dire need of some love.

Have just been incredibly busy with work.  That should be letting up soon, so I'll have some more free time to work on side projects.

If someone wants to step forward to help co-maintain, that would be much appreciated.

**Comment by epcim** [comment]
I fired #86 pull request - that's draft version for 7.7 that is somehow working for me. I actually have the issue with kitchen tests that fails on my environment, due chef order issue with redision, mysql. Note since mysql cookbook 6.x upgraded to provide only LWRP, but no myslq:server recipe as in the past I install it as a part of gitlab cookbook.

**Comment by jeremyolliver** [comment]
Closing this issue as #86 is now merged
